language: php

php:
  - 5.4
  - 5.5

before_script:
 - wget https://scrutinizer-ci.com/ocular.phar

script:
 - ant travis -keep-going

after_script:
 - php vendor/bin/coveralls -v
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.php

notifications:
  email: false
